replicas: 1
minimumMasterNodes: 1
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "ebs-sc"
  resources:
    requests:
      storage: 10Gi
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "250m"
      memory: "512M"